### passed 1
GET {{host}}/status/200

> {%
    client.test("Status code is 200", function (){
        client.assert(response.status === 200, "Response status is not 200")
    });
%}

### passed 2
GET {{host}}/status/200

> {%
    client.test("Status code is 200", function (){
        client.assert(response.status === 200, "Response status is not 200")
    });
%}

### passed 3
GET {{host}}/status/200

> {%
    client.test("Status code is 200", function (){
        client.assert(response.status === 200, "Response status is not 200")
    });
%}

### passed 4
GET {{host}}/status/200

> {%
    client.test("Status code is 200", function (){
        client.assert(response.status === 200, "Response status is not 200")
    });
%}

### passed 5
GET {{host}}/status/200

> {%
    client.test("Status code is 200", function (){
        client.assert(response.status === 200, "Response status is not 200")
    });
%}

### passed 6
GET {{host}}/status/200

> {%
    client.test("Status code is 200", function (){
        client.assert(response.status === 200, "Response status is not 200")
    });
%}

### passed 7
GET {{host}}/status/200

> {%
    client.test("Status code is 200", function (){
        client.assert(response.status === 200, "Response status is not 200")
    });
%}

### passed 8
GET {{host}}/status/200

> {%
    client.test("Status code is 200", function (){
        client.assert(response.status === 200, "Response status is not 200")
    });
%}

### passed 9
GET {{host}}/status/200

> {%
    client.test("Status code is 200", function (){
        client.assert(response.status === 200, "Response status is not 200")
    });
%}

### passed 10
GET {{host}}/status/200

> {%
    client.test("Status code is 200", function (){
        client.assert(response.status === 200, "Response status is not 200")
    });
%}
